src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Impossible de créer un compte utilisateur avec cet email")
 */
class User implements UserInterface
{
    use ResourceId;
    use Timestapable;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $email;

    /**
     * @ORM\Column(type="json")
     * @var array<string>
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected string $username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private string $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private string $lastname;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected ?\DateTime $lastConnexionAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $telephone;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isTermsClients;

    /**
     * @ORM\OneToOne(targetEntity=Profile::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private ?Profile $profile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $forgotPasswordToken;

    private ?DateTimeImmutable $lastConnextionAt;

    /**
     * @return string|null
     */
    public function getForgotPasswordToken(): ?string
    {
        return $this->forgotPasswordToken;
    }

    /**
     * @param string|null $forgotPasswordToken
     */
    public function setForgotPasswordToken(?string $forgotPasswordToken): void
    {
        $this->forgotPasswordToken = $forgotPasswordToken;
    }

    /**
     * @return DateTimeImmutable|null
     */
    public function getForgotPasswordTokenRequestedAt(): ?DateTimeImmutable
    {
        return $this->forgotPasswordTokenRequestedAt;
    }

    /**
     * @param DateTimeImmutable|null $forgotPasswordTokenRequestedAt
     */
    public function setForgotPasswordTokenRequestedAt(?DateTimeImmutable $forgotPasswordTokenRequestedAt): void
    {
        $this->forgotPasswordTokenRequestedAt = $forgotPasswordTokenRequestedAt;
    }

    /**
     * @return DateTimeImmutable|null
     */
    public function getForgotPasswordTokenMustBeVerifiedBefore(): ?DateTimeImmutable
    {
        return $this->forgotPasswordTokenMustBeVerifiedBefore;
    }

    /**
     * @param DateTimeImmutable|null $forgotPasswordTokenMustBeVerifiedBefore
     */
    public function setForgotPasswordTokenMustBeVerifiedBefore(?DateTimeImmutable $forgotPasswordTokenMustBeVerifiedBefore): void
    {
        $this->forgotPasswordTokenMustBeVerifiedBefore = $forgotPasswordTokenMustBeVerifiedBefore;
    }

    /**
     * @return DateTimeImmutable|null
     */
    public function getForgotPasswordTokenVerifiedAt(): ?DateTimeImmutable
    {
        return $this->forgotPasswordTokenVerifiedAt;
    }

    /**
     * @param DateTimeImmutable|null $forgotPasswordTokenVerifiedAt
     */
    public function setForgotPasswordTokenVerifiedAt(?DateTimeImmutable $forgotPasswordTokenVerifiedAt): void
    {
        $this->forgotPasswordTokenVerifiedAt = $forgotPasswordTokenVerifiedAt;
    }

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?DateTimeImmutable $forgotPasswordTokenRequestedAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?DateTimeImmutable $forgotPasswordTokenMustBeVerifiedBefore;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?DateTimeImmutable $forgotPasswordTokenVerifiedAt;

    /**
     * @ORM\OneToMany(targetEntity=Candidature::class, mappedBy="candidat")
     */
    private Collection $candidatures;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private ?string $activation_token;

    /**
     * @ORM\ManyToMany(targetEntity=Entreprise::class, mappedBy="recruteurs")
     */
    private Collection $entreprises;

    /**
     * @ORM\ManyToMany(targetEntity=Entreprise::class, mappedBy="super_recruteurs")
     */
    private Collection $recruteurs_entreprise;

    /**
     * @ORM\OneToMany(targetEntity=File::class, mappedBy="user", orphanRemoval=true, cascade={"persist"})
     */
    private Collection $files;

    /**
     * @ORM\ManyToMany(targetEntity=Annonce::class, mappedBy="auteur")
     */
    private Collection $annonces_auteurs;

    public function __construct()
    {
        $this->isTermsClients = false;
        $this->roles = ['ROLE_CANDIDAT'];
        $this->candidatures = new ArrayCollection();
        $this->entreprises = new ArrayCollection();
        $this->recruteurs_entreprise = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->annonces_auteurs = new ArrayCollection();
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_CANDIDAT';

        return array_unique($roles);
    }

    /**
     * set the user role
     *
     * @param array<string> $roles
     * @return self
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getLastConnexionAt(): ?\DateTimeInterface
    {
        return $this->lastConnextionAt;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getIsTermsClients(): ?bool
    {
        return $this->isTermsClients;
    }

    public function setIsTermsClients(bool $isTermsClients): self
    {
        $this->isTermsClients = $isTermsClients;

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(?Profile $profile): self
    {
        // unset the owning side of the relation if necessary
        if ($profile === null && $this->profile !== null) {
            $this->profile->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($profile !== null && $profile->getUser() !== $this) {
            $profile->setUser($this);
        }

        $this->profile = $profile;

        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->getEmail();
    }

    public function getOneRecruteurEntreprise(): string
    {
        $result = array();
        foreach($this->getEntreprises() as $entreprise){
            $result[] ="<b>Recruteur</b>" . ' ' . $entreprise->getName() . '<br/>';
        }
        foreach($this->getRecruteursEntreprise() as $entreprise){
            $result[] ="<b>Super Recruteur</b>" . ' ' . $entreprise->getName() . '<br/>';
        }

        return $this->getEmail() . "<br/><br>" . implode('<br/>', $result);
    }

    /**
     * @return string
     */
    public function getFullname(): string
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function isCandidat(): bool
    {
        $role = "ROLE_CANDIDAT";
        return $this->checkRoles($role);
    }

    public function isRecruteur(): bool
    {
        $role = "ROLE_RECRUTEUR";
        return $this->checkRoles($role);
    }

    public function isSuperRecruteur(): bool
    {
        $role = "ROLE_SUPER_RECRUTEUR";
        return $this->checkRoles($role);
    }

src/Controller/UserCreationController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

#[Route('/user/creation')]
class UserCreationController extends AbstractController
{
    #[Route('/', name: 'user_creation', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user_creation/index.html.twig', [
            'users' => $userRepository->getRecruteurs($this->getUser()->getId()),
        ]);
    }

    /*#[Route('/new', name: 'user_creation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder, MailerInterface $mailer): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setRoles(['ROLE_RECRUTEUR']);
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            $user->setActivationToken(md5(uniqid()));

            $entityManager = $this->getDoctrine()->getManager();

            $entreprises = $form->get('entreprises')->getData();

            foreach ($entreprises as $entrepriseId){
                $entreprise = $entityManager->getRepository('App\Entity\Entreprise')->find($entrepriseId);
                $entreprise->addRecruteur($user);
            }

            $entityManager->persist($user);
            $entityManager->flush();

            $email = (new TemplatedEmail())
                ->from('haha@gmail.com')
                ->to('oyo@gmail.com')
                ->subject('Activation de compte!')
                ->text('Sending emails is fun again!')
                ->htmlTemplate('emails/creation.html.twig')
                ->context(['token' => $user->getActivationToken()])
            ;

            $mailer->send($email);

            $this->addFlash('success', 'Le compte a été créé');
            return $this->redirectToRoute('user_creation');
        }

        return $this->render('user_creation/index.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }*/

    #[Route('/{id}', name: 'user_creation_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user_creation/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'user_creation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_creation');
        }

        return $this->render('user_creation/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'user_creation_delete', methods: ['POST'])]
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_creation');
    }

    #[Route('/activation/{token}', name: 'activation')]
    public function activation($token, UserRepository $userRepository): Response
    {
        $user = $userRepository->findOneBy(['activation_token' => $token]);
        if(!$user){
            throw $this->createNotFoundException('Cet utilisateur n\'existe pas');
        }

        $user->setActivationToken(null);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();

        $this->addFlash('success', 'Vous avez bien activé votre compte');

        return $this->render('home/index.html.twig');
    }

}

templates/user_creation/_delete_form.html.twig
<form method="post" action="{{ path('user_creation_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user_creation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <main id="main">
        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="{{ path('app_home') }}">Home</a></li>
                    <li><a href="{{ path('app_profile') }}">Dashboard</a></li>
                    <li><a href="{{ path('offre_index') }}">Recruteurs</a></li>
                    <li>Modification</li>
                </ol>
                <h2>Modification d'un recruteur</h2>
            </div>
        </section><!-- End Breadcrumbs -->
        <section class="inner-page">
            <div class="container">
                {{ include('user_creation/_form.html.twig') }}
            </div>
        </section>
    </main>
{% endblock %}

templates/user_creation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recruteurs{% endblock %}

{% block body %}
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{{ path('app_home') }}">Home</a></li>
                <li><a href="{{ path('app_profile') }}">Dashboard</a></li>
                <li>Répértoire</li>
            </ol>
            <h2>Gestion des recruteurs</h2>

        </div>
    </section><!-- End Breadcrumbs -->
    <section class="inner-page">
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Entreprises</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.fullname }}</td>
                        <td>{{ user.entreprises|join() }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {#<a href="{{ path('user_creation_new') }}" class="btn btn-primary">Create new</a>#}
        </div>
    </section>
</main>
{% endblock %}

templates/user_creation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{{ path('app_home') }}">Home</a></li>
                <li><a href="{{ path('app_profile') }}">Dashboard</a></li>
                <li><a href="{{ path('offre_index') }}">Recruteurs</a></li>
                <li>Création</li>
            </ol>
            <h2>Création d'un recruteur</h2>
        </div>
    </section><!-- End Breadcrumbs -->
    <section class="inner-page">
        <div class="container">
            {{ include('user_creation/_form.html.twig') }}
        </div>
    </section>
</main>
{% endblock %}

templates/user_creation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ user.lastname }}</td>
            </tr>
            <tr>
                <th>LastConnexionAt</th>
                <td>{{ user.lastConnexionAt ? user.lastConnexionAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ user.telephone }}</td>
            </tr>
            <tr>
                <th>IsTermsClients</th>
                <td>{{ user.isTermsClients ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>ForgotPasswordToken</th>
                <td>{{ user.forgotPasswordToken }}</td>
            </tr>
            <tr>
                <th>ForgotPasswordTokenRequestedAt</th>
                <td>{{ user.forgotPasswordTokenRequestedAt ? user.forgotPasswordTokenRequestedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>ForgotPasswordTokenMustBeVerifiedBefore</th>
                <td>{{ user.forgotPasswordTokenMustBeVerifiedBefore ? user.forgotPasswordTokenMustBeVerifiedBefore|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>ForgotPasswordTokenVerifiedAt</th>
                <td>{{ user.forgotPasswordTokenVerifiedAt ? user.forgotPasswordTokenVerifiedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_creation_index') }}">back to list</a>

    <a href="{{ path('user_creation_edit', {'id': user.id}) }}">edit</a>

    {{ include('user_creation/_delete_form.html.twig') }}
{% endblock %}